In [3]:
import numpy as np

In [1]:
# 1.Write a NumPy program to generate six random integers between 10 and 30.

r = np.random.randint(10,30,6)
print(r)

[26 19 29 18 11 23]


In [4]:
# 2.Write a NumPy program to create a 3x3 matrix with values ranging from 20to 28

m =  np.arange(20,29).reshape(3,3)
print(m)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [6]:
# 3.Write a NumPy program to create a vector filled with 1s of size 10 and update the sixth value to 25

ones = np.ones(10)
print('Before adding 25',ones)
ones[6] = 25
print('After adding 25',ones)

Before adding 25 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After adding 25 [ 1.  1.  1.  1.  1.  1. 25.  1.  1.  1.]


In [7]:
# 4.Write a program to get fourth and seventh elements from the following array and add them.

arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[3] + arr[6])

110


In [8]:
# 5.Write a program to get the first three elements of the second column of the array

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(arr[0:3, 1])

[2 5 8]
